"""Add thesis_file

Revision ID: 50a72c7d3d3a
Revises: 39ab8c5ca99f
Create Date: 2026-02-07 07:50:06.263294

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '50a72c7d3d3a'
down_revision = '39ab8c5ca99f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocation', sa.Column('thesis_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocation', 'thesis_file')
    # ### end Alembic commands ###
